// frontend/src/pages/Register.tsx
import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import {
  Box,
  Button,
  Card,
  CardActions,
  CardContent,
  CircularProgress,
  TextField,
  Typography,
  Alert,
} from '@mui/material'

import { authApi } from '../api/auth'

export default function RegisterPage() {
  const navigate = useNavigate()
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  async function handleSubmit(event: FormEvent) {
    event.preventDefault()
    setLoading(true)
    setError('')
    try {
      await authApi.register({
        email,
        password,
        first_name: firstName || undefined,
        last_name: lastName || undefined,
      })
      navigate('/login')
    } catch (err: unknown) {
      const detail = (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      setError(detail ?? 'Registration failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', bgcolor: '#f5f5f5' }}>
      <Card sx={{ width: '100%', maxWidth: 440, p: 3 }}>
        <CardContent>
          <Typography variant="h5" component="h1" sx={{ fontWeight: 'bold' }}>
            Register
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
            Create your SupportAI account
          </Typography>
          <Box component="form" onSubmit={handleSubmit} sx={{ mt: 3, display: 'flex', flexDirection: 'column', gap: 2 }}>
            {error && <Alert severity="error">{error}</Alert>}
            <Box sx={{ display: 'flex', gap: 2 }}>
              <TextField
                label="First Name"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                fullWidth
              />
              <TextField
                label="Last Name"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                fullWidth
              />
            </Box>
            <TextField
              label="Email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              fullWidth
              autoComplete="email"
            />
            <TextField
              label="Password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              fullWidth
              autoComplete="new-password"
              helperText="At least 8 characters with uppercase, lowercase, and a number"
            />
            <Button type="submit" variant="contained" color="primary" size="large" disabled={loading} fullWidth>
              {loading && <CircularProgress size={20} sx={{ mr: 1 }} />}
              {!loading && 'Register'}
            </Button>
          </Box>
        </CardContent>
        <CardActions sx={{ justifyContent: 'center', pb: 2 }}>
          <Button component={Link} to="/login" size="small">
            Already have an account? Login
          </Button>
        </CardActions>
      </Card>
    </Box>
  )
}

// frontend/src/app/features/auth/register/register.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

import { AuthService } from '../../../core/auth/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    FormsModule,
    RouterLink,
    MatCardModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
  ],
  template: `
    <div class="flex items-center justify-center min-h-screen bg-gray-100">
      <mat-card class="w-full max-w-md p-8">
        <mat-card-header>
          <mat-card-title class="text-2xl font-bold">Register</mat-card-title>
          <mat-card-subtitle>Create your SupportAI account</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content class="mt-4">
          <form (ngSubmit)="onSubmit()" #registerForm="ngForm">
            <div class="flex gap-3">
              <mat-form-field appearance="outline" class="w-full">
                <mat-label>First Name</mat-label>
                <input matInput [(ngModel)]="firstName" name="firstName" placeholder="First name">
              </mat-form-field>
              <mat-form-field appearance="outline" class="w-full">
                <mat-label>Last Name</mat-label>
                <input matInput [(ngModel)]="lastName" name="lastName" placeholder="Last name">
              </mat-form-field>
            </div>
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Email</mat-label>
              <input matInput type="email" [(ngModel)]="email" name="email" required email placeholder="Enter your email">
            </mat-form-field>
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Password</mat-label>
              <input matInput type="password" [(ngModel)]="password" name="password" required minlength="8" placeholder="Enter your password">
              <mat-hint>At least 8 characters with uppercase, lowercase, and a number</mat-hint>
            </mat-form-field>
            @if (errorMessage) {
              <mat-error class="mb-2">
                {{ errorMessage }}
              </mat-error>
            }
            <button mat-raised-button color="primary" class="w-full" type="submit" [disabled]="loading || registerForm.invalid">
              @if (loading) {
                <mat-spinner diameter="20" class="inline-block mr-2"></mat-spinner>
              } @else {
                <span>Register</span>
              }
            </button>
          </form>
        </mat-card-content>
        <mat-card-actions>
          <a mat-button routerLink="/login" class="w-full text-center">Already have an account? Login</a>
        </mat-card-actions>
      </mat-card>
    </div>
  `,
})
export class RegisterComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  firstName = '';
  lastName = '';
  email = '';
  password = '';
  loading = false;
  errorMessage = '';

  onSubmit(): void {
    if (this.loading) {
      return;
    }
    this.loading = true;
    this.errorMessage = '';
    this.authService
      .register({
        email: this.email,
        password: this.password,
        first_name: this.firstName || undefined,
        last_name: this.lastName || undefined,
      })
      .subscribe({
        next: () => {
          this.loading = false;
          this.router.navigate(['/login']);
        },
        error: (err) => {
          this.loading = false;
          this.errorMessage = err?.error?.detail ?? 'Registration failed. Please try again.';
        },
      });
  }
}
