// frontend/src/app/layout/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, MatIconModule, MatListModule],
  template: `
    <div class="sidebar">
      <div class="sidebar-brand">
        <mat-icon>support_agent</mat-icon>
        <span>SupportAI</span>
      </div>
      <mat-nav-list>
        <a mat-list-item routerLink="/dashboard" routerLinkActive="active-link">
          <mat-icon matListItemIcon>dashboard</mat-icon>
          <span matListItemTitle>Dashboard</span>
        </a>
        <a mat-list-item routerLink="/conversations" routerLinkActive="active-link">
          <mat-icon matListItemIcon>chat</mat-icon>
          <span matListItemTitle>Conversations</span>
        </a>
        <a mat-list-item routerLink="/knowledge-base" routerLinkActive="active-link">
          <mat-icon matListItemIcon>library_books</mat-icon>
          <span matListItemTitle>Knowledge Base</span>
        </a>
        <a mat-list-item routerLink="/tickets" routerLinkActive="active-link">
          <mat-icon matListItemIcon>confirmation_number</mat-icon>
          <span matListItemTitle>Tickets</span>
        </a>
        <a mat-list-item routerLink="/evaluations" routerLinkActive="active-link">
          <mat-icon matListItemIcon>assessment</mat-icon>
          <span matListItemTitle>Evaluations</span>
        </a>
        <a mat-list-item routerLink="/analytics" routerLinkActive="active-link">
          <mat-icon matListItemIcon>analytics</mat-icon>
          <span matListItemTitle>Analytics</span>
        </a>
        <a mat-list-item routerLink="/settings" routerLinkActive="active-link">
          <mat-icon matListItemIcon>settings</mat-icon>
          <span matListItemTitle>Settings</span>
        </a>
      </mat-nav-list>
    </div>
  `,
  styles: [`
    .sidebar {
      width: 250px;
      height: 100%;
      background: #1a1a2e;
      color: white;
      display: flex;
      flex-direction: column;
    }
    .sidebar-brand {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 16px;
      font-size: 18px;
      font-weight: 500;
      border-bottom: 1px solid rgba(255,255,255,0.1);
    }
    mat-nav-list {
      flex: 1;
      padding-top: 8px;
    }
    a {
      color: rgba(255,255,255,0.7);
      margin: 2px 8px;
      border-radius: 8px;
    }
    a:hover {
      background: rgba(255,255,255,0.1);
      color: white;
    }
    .active-link {
      background: rgba(103, 58, 183, 0.3) !important;
      color: white !important;
    }
  `]
})
export class SidebarComponent {}

// frontend/src/layout/Sidebar.tsx
import { NavLink } from 'react-router-dom'
import { Box, List, ListItemButton, ListItemIcon, ListItemText, Typography } from '@mui/material'
import DashboardIcon from '@mui/icons-material/Dashboard'
import ChatIcon from '@mui/icons-material/Chat'
import LibraryBooksIcon from '@mui/icons-material/LibraryBooks'
import ConfirmationNumberIcon from '@mui/icons-material/ConfirmationNumber'
import AssessmentIcon from '@mui/icons-material/Assessment'
import AnalyticsIcon from '@mui/icons-material/Analytics'
import SettingsIcon from '@mui/icons-material/Settings'
import SupportAgentIcon from '@mui/icons-material/SupportAgent'

const navItems = [
  { to: '/dashboard', label: 'Dashboard', icon: <DashboardIcon /> },
  { to: '/conversations', label: 'Conversations', icon: <ChatIcon /> },
  { to: '/knowledge-base', label: 'Knowledge Base', icon: <LibraryBooksIcon /> },
  { to: '/tickets', label: 'Tickets', icon: <ConfirmationNumberIcon /> },
  { to: '/evaluations', label: 'Evaluations', icon: <AssessmentIcon /> },
  { to: '/analytics', label: 'Analytics', icon: <AnalyticsIcon /> },
  { to: '/settings', label: 'Settings', icon: <SettingsIcon /> },
]

export function Sidebar() {
  return (
    <Box
      sx={{
        width: 250,
        height: '100%',
        bgcolor: '#1a1a2e',
        color: 'white',
        display: 'flex',
        flexDirection: 'column',
        flexShrink: 0,
      }}
    >
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, p: 2, fontSize: 18, fontWeight: 500, borderBottom: '1px solid rgba(255,255,255,0.1)' }}>
        <SupportAgentIcon />
        <span>SupportAI</span>
      </Box>
      <List sx={{ flex: 1, p: 1 }}>
        {navItems.map((item) => (
          <ListItemButton
            key={item.to}
            component={NavLink}
            to={item.to}
            sx={{
              color: 'rgba(255,255,255,0.7)',
              mb: 0.5,
              borderRadius: 2,
              '&.active': {
                bgcolor: 'rgba(103, 58, 183, 0.3)',
                color: 'white',
              },
              '&:hover': {
                bgcolor: 'rgba(255,255,255,0.1)',
                color: 'white',
              },
            }}
          >
            <ListItemIcon sx={{ color: 'inherit', minWidth: 36 }}>{item.icon}</ListItemIcon>
            <ListItemText primary={<Typography variant="body2">{item.label}</Typography>} />
          </ListItemButton>
        ))}
      </List>
    </Box>
  )
}
